%%
gclk_freq = 12e6;
i2c_scl_freq = 100000;
Trise = 215;
BAUD_BAUDLOW = ...
  floor( ...
    ((gclk_freq ...
       - (i2c_scl_freq*10) ...
       - floor( ...
            floor(gclk_freq/10000) ...
              *floor(i2c_scl_freq/100) ...
              *Trise ...
              /1000)) ...
           *10+5) ...
          / (i2c_scl_freq*10));
if bitand(BAUD_BAUDLOW,1)
  BAUD_RATE = floor(BAUD_BAUDLOW/2) + ceil(BAUD_BAUDLOW/2)*2^8;
else
  BAUD_RATE = BAUD_BAUDLOW/2;
end
fprintf(1,'-----------------------------------\n');
fprintf(1,'Core Clock frequency = %.0f\n', gclk_freq);
fprintf(1,'Target I2C frequency = %.0f\n', i2c_scl_freq);
fprintf(1,'BAUD+BAUDLOW = %d\n', BAUD_BAUDLOW);
if BAUD_BAUDLOW > 255*2
  fprintf(1, 'Baud Rate too low\n');
elseif BAUD_BAUDLOW <= 1
  fprintf(1, 'Baud Rate too high\n');
else
  fprintf(1,'BAUD_RATE = 0x%04X\n', BAUD_RATE);
end
